export const experienceData = [
  {
    role: "Software Engineer | Full-Stack Systems & Performance Optimization",
    company: "Uforia Infotech",
    location: "Islamabad, Pakistan",
    period: "Sep 2025 – Present",
    description:
      "Working as a full-stack software engineer building scalable applications, optimizing system performance, and integrating backend services with modern interactive frontends in production environments.",
    technologies: [
      "React",
      "Node.js",
      "Flask",
      "Python",
      "JavaScript",
      "SQL",
      "REST APIs",
      "Docker",
      "AWS",
      "GCP",
    ],
    accomplishments: [
      "Developed and integrated backend APIs with responsive frontend interfaces for production applications.",
      "Optimized core modules for performance, stability, and maintainability.",
      "Improved system efficiency through code refactoring and modular architecture design.",
      "Collaborated in cross-functional teams to streamline deployment and integration workflows.",
      "Maintained technical documentation for APIs, dependencies, and system architecture.",
    ],
  },
  {
    role: "AI Engineer | LLMs, RAG, Federated Learning & Privacy-Preserving AI",
    company: "Independent / Freelance Projects",
    location: "Remote",
    period: "2024 – 2025",
    description:
      "Designed and deployed scalable AI systems combining large language models, retrieval-augmented generation pipelines, and privacy-preserving machine learning architectures.",
    technologies: [
      "Python",
      "PyTorch",
      "TensorFlow",
      "LangChain",
      "Qdrant",
      "CLIP",
      "Flask",
      "FastAPI",
      "React",
      "AWS",
      "GCP",
    ],
    accomplishments: [
      "Built Pak-Law GPT, a bilingual legal RAG assistant using vector search, prompt orchestration, and structured retrieval pipelines.",
      "Developed decentralized federated learning pipelines for ocular disease diagnosis achieving >99% accuracy on ODIR-5K.",
      "Implemented privacy-preserving FL mesh topology with secure aggregation and optimized communication strategies.",
      "Designed AI agents and inference pipelines integrating multimodal embeddings and domain-specific retrieval.",
      "Deployed scalable AI services with real-time inference and monitoring on cloud infrastructure.",
    ],
  },
  {
    role: "AI Research Engineer | Federated Learning, NLP & Medical AI",
    company: "Freelance Projects",
    location: "Islamabad, Pakistan",
    period: "Aug 2024 – Present",
    description:
      "Conducting applied research in federated learning, computer vision, and privacy-preserving AI systems with focus on decentralized model training and performance optimization.",
    technologies: [
      "PyTorch",
      "TensorFlow",
      "Flower",
      "BiLSTM",
      "Swin Transformer",
      "EfficientNet",
      "Python",
      "Google Colab",
    ],
    accomplishments: [
      "Published IEEE Access paper on sarcasm detection using attention-enhanced BiLSTM under federated learning.",
      "Designed decentralized training architecture for ocular disease classification using EfficientNet-B0 and Swin Transformer.",
      "Implemented precision-weighted aggregation and secure communication for multi-client FL systems.",
      "Led experimentation on model optimization, evaluation metrics, and distributed training strategies.",
      "Contributed to multiple peer-reviewed research papers in NLP and medical AI.",
    ],
  },
  {
    role: "MERN Stack Developer Intern",
    company: "Eziline Software House (Pvt) Ltd.",
    location: "Rawalpindi, Pakistan",
    period: "Jun 2023 – Sep 2023",
    description:
      "Completed a professional internship focused on building full-stack web applications using the MERN ecosystem with emphasis on scalable backend architecture and clean UI development.",
    technologies: [
      "MongoDB",
      "Express.js",
      "React",
      "Node.js",
      "JavaScript",
      "REST APIs",
    ],
    accomplishments: [
      "Developed a School Management System with scalable CRUD architecture.",
      "Built a full e-commerce platform with authentication and product management.",
      "Implemented an interactive online quiz system with real-time evaluation.",
      "Delivered high-quality production-ready code while maintaining perfect attendance.",
    ],
    url: "https://www.eziline.com/",
  },
];